Add support for arm64
rancher/istio-installer pull request #67
Opened 2023-11-21 21:29 UTC by CC007

This changes the drone.io build, so that it creates an amd64 specific tag and an arm64 specific tag, after which it creates a manifest, which combines the two. 

The combined version will be published with the original tag conventions (so without the arch suffix)

Fixes https://github.com/rancher/rancher/issues/43578

2023-11-24 06:58 UTC, rohitsakala approved these changes

2023-11-24 11:27 UTC, rohitsakala requested changes
Before I merge, I have a question. Do you want arm support for 1.18 Istio ? or 1.19 Istio ? 

We will releasing the latest version of Istio i.e 1.19 soonish. We would prefer 1.19 if that okay. Changed the base branch to release/1.19.

2023-11-24 15:26 UTC, CC007 commented
I would like it to be available for both rancher 2.7.x and  newer and preferably as fast as possible.

2023-11-24 16:19 UTC, rohitsakala commented
Can you make a separate PR for the release/1.18 branch as well ?

2023-11-24 16:20 UTC, merged

2023-11-24 21:23 UTC, CC007 commented
> Can you make a separate PR for the release/1.18 branch as well ?

Done

2023-11-25 02:19 UTC, CC007 commented
Looks like since I branched off of master, that there's unnecessary complexity in the branching graph. Also, I'm surprised that the master branch is still on v1.11.4